CREATE TABLE `automobile_listings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` integer NOT NULL,
	`title` text NOT NULL,
	`category` text NOT NULL,
	`subcategory` text NOT NULL,
	`duration` text NOT NULL,
	`description` text NOT NULL,
	`media` text,
	`make` text NOT NULL,
	`model` text NOT NULL,
	`built_in_year` text NOT NULL,
	`body` text NOT NULL,
	`fuel` text NOT NULL,
	`transmission` text NOT NULL,
	`engine` text NOT NULL,
	`drive` text NOT NULL,
	`odometer` text NOT NULL,
	`odometer_unit` text NOT NULL,
	`condition` text NOT NULL,
	`accident_history` text NOT NULL,
	`history` text,
	`service_history` text NOT NULL,
	`owner` text NOT NULL,
	`vin_number` text NOT NULL,
	`automobile_country` text NOT NULL,
	`automobile_state` text NOT NULL,
	`automobile_city` text NOT NULL,
	`automobile_pincode` text,
	`price` text NOT NULL,
	`negotiable` text,
	`mobile_feature` text,
	`warranty` text NOT NULL,
	`warranty_details` text,
	`created_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `business_listings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` integer NOT NULL,
	`title` text NOT NULL,
	`category` text NOT NULL,
	`subcategory` text NOT NULL,
	`auction_type` text NOT NULL,
	`duration` text NOT NULL,
	`description` text NOT NULL,
	`media` text,
	`built_in_year` text,
	`business_address` text,
	`business_country` text,
	`business_state` text,
	`business_city` text,
	`business_pincode` text,
	`highlight` text,
	`reason` text,
	`price` text,
	`revenue` text,
	`profit` text,
	`assets` text,
	`inventory` text,
	`inventory_value` text,
	`employes` text,
	`involvement` text,
	`relocatable` text,
	`homebase` text,
	`franchise` text,
	`name_franchise` text,
	`premises` text,
	`monthly` text,
	`expiry` text,
	`facility_size` text,
	`created_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `real_estate_listings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` integer NOT NULL,
	`title` text NOT NULL,
	`category` text NOT NULL,
	`subcategory` text NOT NULL,
	`auction_type` text NOT NULL,
	`duration` text NOT NULL,
	`description` text NOT NULL,
	`media` text,
	`property_address` text NOT NULL,
	`property_country` text NOT NULL,
	`property_state` text NOT NULL,
	`property_city` text NOT NULL,
	`property_pincode` text,
	`bedroom` text,
	`bathroom` text,
	`area` text,
	`price` text,
	`built_in_year` text,
	`furnishing` text,
	`utilities` text,
	`features` text,
	`auction_price` text,
	`auction_date` text,
	`expiry` text,
	`ownership_type` text,
	`ownership_title` text,
	`ownership_status` text,
	`legal_description` text,
	`contact_name` text NOT NULL,
	`contact_phone` text NOT NULL,
	`contact_email` text NOT NULL,
	`is_agent` text,
	`license_number` text,
	`authorized_to_sell` text,
	`agree_terms` text,
	`created_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`uid` text NOT NULL,
	`email` text NOT NULL,
	`name` text NOT NULL,
	`password_hash` text NOT NULL,
	`role` text DEFAULT 'user',
	`is_verified` integer DEFAULT false NOT NULL,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);