import { sqliteTable, uniqueIndex, integer, text } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const users = sqliteTable("users", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	uid: text().notNull(),
	email: text().notNull(),
	name: text().notNull(),
	passwordHash: text("password_hash").notNull(),
	role: text().default("user"),
	createdAt: integer("created_at").default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`),
	updatedAt: integer("updated_at").default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`),
	isVerified: integer("is_verified").default(0).notNull(),
},
(table) => [
	uniqueIndex("users_email_unique").on(table.email),
]);

export const realEstateListings = sqliteTable("real_estate_listings", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	userId: integer("user_id").notNull(),
	title: text().notNull(),
	category: text().notNull(),
	subcategory: text().notNull(),
	auctionType: text("auction_type").notNull(),
	duration: text().notNull(),
	description: text().notNull(),
	media: text(),
	propertyAddress: text("property_address").notNull(),
	propertyCountry: text("property_country").notNull(),
	propertyState: text("property_state").notNull(),
	propertyCity: text("property_city").notNull(),
	propertyPincode: text("property_pincode"),
	bedroom: text(),
	bathroom: text(),
	area: text(),
	lot_size: text(),
	builtInYear: text("built_in_year"),
	furnishing: text(),
	utilities: text(),
	features: text(),
	auctionPrice: text("auction_start_price"),
	auctionDate: text("auction_date"),
	expiry: text(),
	ownershipType: text("ownership_type"),
	ownershipTitle: text("ownership_title"),
	ownershipStatus: text("ownership_status"),
	legalDescription: text("legal_description"),
	contactName: text("contact_name").notNull(),
	contactPhone: text("contact_phone").notNull(),
	contactEmail: text("contact_email").notNull(),
	isAgent: text("is_agent"),
	licenseNumber: text("license_number"),
	authorizedToSell: text("authorized_to_sell"),
	agreeTerms: text("agree_terms"),
	createdAt: integer("created_at").notNull(),
});

export const automobileListings = sqliteTable("automobile_listings", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	userId: integer("user_id").notNull(),
	title: text().notNull(),
	category: text().notNull(),
	subcategory: text().notNull(),
	duration: text().notNull(),
	description: text().notNull(),
	media: text(),
	make: text().notNull(),
	model: text().notNull(),
	builtInYear: text("built_in_year").notNull(),
	body: text().notNull(),
	fuel: text().notNull(),
	transmission: text().notNull(),
	engine: text().notNull(),
	drive: text().notNull(),
	odometer: text().notNull(),
	odometerUnit: text("odometer_unit").notNull(),
	condition: text().notNull(),
	accidentHistory: text("accident_history").notNull(),
	history: text(),
	serviceHistory: text("service_history").notNull(),
	owner: text().notNull(),
	vinNumber: text("vin_number").notNull(),
	automobileCountry: text("automobile_country").notNull(),
	automobileState: text("automobile_state").notNull(),
	automobileCity: text("automobile_city").notNull(),
	automobilePincode: text("automobile_pincode"),
	price: text().notNull(),
	negotiable: text(),
	mobileFeature: text("mobile_feature"),
	warranty: text().notNull(),
	warrantyDetails: text("warranty_details"),
	createdAt: integer("created_at").notNull(),
});

export const businessListings = sqliteTable("business_listings", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	userId: integer("user_id").notNull(),
	title: text().notNull(),
	category: text().notNull(),
	subcategory: text().notNull(),
	auctionType: text("auction_type").notNull(),
	duration: text().notNull(),
	description: text().notNull(),
	media: text(),
	builtInYear: text("built_in_year"),
	businessAddress: text("business_address"),
	businessCountry: text("business_country"),
	businessState: text("business_state"),
	businessCity: text("business_city"),
	businessPincode: text("business_pincode"),
	highlight: text(),
	reason: text(),
	price: text(),
	revenue: text(),
	profit: text(),
	assets: text(),
	inventory: text(),
	inventoryValue: text("inventory_value"),
	employes: text(),
	involvement: text(),
	relocatable: text(),
	homebase: text(),
	franchise: text(),
	nameFranchise: text("name_franchise"),
	premises: text(),
	monthly: text(),
	expiry: text(),
	facilitySize: text("facility_size"),
	createdAt: integer("created_at").notNull(),
});

